# Generated by Django 5.0.1 on 2024-01-19 18:55

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
